[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "2FqJcVjBU9dt4PvWSnXD7KJhBNEoJs5T5j9y8SZKXFMV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
